### ISSUE TITLE
Feature selection

### ISSUE THREAD

**Issue by asadisaghar** [asadisaghar/TimeDelay#1]
- http://scikit-learn.org/stable/modules/feature_selection.html
- Fourier residual between pair LCs
- Derive the host galaxy LC from single observed LCs + add coupling as a constraint
- Note from time series analysis:
  When the noise is high compared to the signal, or the signal has a
  complex shape (i.e., it is not a simple harmonic function), a probabilistic treatment
  (e.g., Bayesian analysis) offers substantial improvements, and for irregularly (un-
  evenly) sampled data probabilistic treatment becomes essential. For these reasons,
  in the analysis of astronomical time series, which are often irregularly sampled with
  heteroscedastic errors, Fourier analysis is often replaced by other methods (such
  as the periodogram analysis

**Comment by redhog** [comment]
- For a set of (relatively prime) intervals, take samples at those intervals and calculate the average for each of the time curves. Use absolute value of difference between the two averages for each interval as features.
