### ISSUE TITLE
autocorrelation

### ISSUE THREAD

**Issue by asadisaghar** [asadisaghar/TimeDelay#3]
why does the autocorrelation of the two signal within each sampling window is EXACTLY the same for both light curves?

**Comment by asadisaghar** [comment]
because correlate apparently identifies the end of each window as the period of the signal. so the maxcorr for autocorrelation is always (time[window][-1] - time[window][0]) / 2

**Comment by redhog** [comment]
How do you avoid this / how can we make it not identify that as the signal period? Is it unable to identify signals with a longer period than the sample window?

**Comment by asadisaghar** [comment]
I don't know. But this is not one of the things we want to measure.
